// <auto-generated />
using System;
using CrimeDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrimeDatabase.Migrations
{
    [DbContext(typeof(CrimeDatabaseContext))]
    [Migration("20250116163902_InitialCrimeEventDB")]
    partial class InitialCrimeEventDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrimeDatabase.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CrimeEventID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrimeEventID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("CrimeDatabase.Models.CrimeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CrimeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrimeType")
                        .HasColumnType("int");

                    b.Property<string>("LocationArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CrimeEvent");
                });

            modelBuilder.Entity("CrimeDatabase.Models.AuditLog", b =>
                {
                    b.HasOne("CrimeDatabase.Models.CrimeEvent", "CrimeEvent")
                        .WithMany()
                        .HasForeignKey("CrimeEventID");

                    b.Navigation("CrimeEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
